import { Animal, TranslationStrings, Language } from './types';

export const ANIMALS: Animal[] = [
  {
    id: 1,
    name: "Buddy",
    breed: "Golden Retriever",
    age: "2 years",
    type: "dog",
    gender: "Male",
    size: "Large",
    image: "https://picsum.photos/id/1025/800/800",
    description_en: "Buddy is a cheerful Golden Retriever who loves fetch and belly rubs. He is great with kids and other dogs.",
    description_tr: "Buddy, yakala oyununu ve göbek kaşınmasını seven neşeli bir Golden Retriever. Çocuklarla ve diğer köpeklerle arası harikadır.",
    tags_en: ["Playful", "Friendly", "Energetic"],
    tags_tr: ["Oyuncu", "Dost Canlısı", "Enerjik"],
    adopted: false,
  },
  {
    id: 2,
    name: "Luna",
    breed: "Siamese Mix",
    age: "1 year",
    type: "cat",
    gender: "Female",
    size: "Small",
    image: "https://picsum.photos/id/1074/800/800", 
    description_en: "Luna is a vocal and affectionate cat. She loves to perch on high shelves and watch birds.",
    description_tr: "Luna konuşkan ve sevecen bir kedi. Yüksek raflara tünemeyi ve kuşları izlemeyi sever.",
    tags_en: ["Vocal", "Curious", "Indoor"],
    tags_tr: ["Konuşkan", "Meraklı", "Evcil"],
    adopted: false,
  },
  {
    id: 3,
    name: "Max",
    breed: "Beagle",
    age: "4 years",
    type: "dog",
    gender: "Male",
    size: "Medium",
    image: "https://picsum.photos/id/237/800/800",
    description_en: "Max is a sniff-expert beagle. He loves long walks and following trails. Very food motivated!",
    description_tr: "Max koku uzmanı bir beagle. Uzun yürüyüşleri ve iz sürmeyi sever. Yemekle arası çok iyidir!",
    tags_en: ["Curious", "Gentle", "Foodie"],
    tags_tr: ["Meraklı", "Nazik", "Obur"],
    adopted: false,
  },
  {
    id: 4,
    name: "Mittens",
    breed: "Domestic Shorthair",
    age: "6 months",
    type: "cat",
    gender: "Female",
    size: "Small",
    image: "https://picsum.photos/id/40/800/800",
    description_en: "Mittens is a shy kitten looking for a quiet home. Once she warms up, she purrs non-stop.",
    description_tr: "Mittens sessiz bir yuva arayan utangaç bir kedi yavrusu. Isındıktan sonra durmadan mırıldanır.",
    tags_en: ["Shy", "Sweet", "Kitten"],
    tags_tr: ["Utangaç", "Tatlı", "Yavru"],
    adopted: true,
  },
  {
    id: 5,
    name: "Rocky",
    breed: "Bulldog",
    age: "3 years",
    type: "dog",
    gender: "Male",
    size: "Medium",
    image: "https://picsum.photos/id/169/800/800",
    description_en: "Rocky looks tough but is a total couch potato. Loves naps and gentle walks.",
    description_tr: "Rocky sert görünür ama tam bir koltuk patatesidir. Şekerlemeleri ve sakin yürüyüşleri sever.",
    tags_en: ["Calm", "Lazy", "Loyal"],
    tags_tr: ["Sakin", "Tembel", "Sadık"],
    adopted: false,
  },
  {
    id: 6,
    name: "Bella",
    breed: "Tabby",
    age: "2 years",
    type: "cat",
    gender: "Female",
    size: "Small",
    image: "https://picsum.photos/id/593/800/800",
    description_en: "Bella is an independent soul who loves sunny spots and laser pointers.",
    description_tr: "Bella güneşli noktaları ve lazerleri seven bağımsız bir ruhtur.",
    tags_en: ["Independent", "Playful", "Hunter"],
    tags_tr: ["Bağımsız", "Oyuncu", "Avcı"],
    adopted: false,
  },
  {
    id: 7,
    name: "Charlie",
    breed: "Border Collie",
    age: "2 years",
    type: "dog",
    gender: "Male",
    size: "Medium",
    image: "https://picsum.photos/id/1062/800/800",
    description_en: "Charlie needs a job to do! Extremely smart and active, looking for an owner who loves hiking.",
    description_tr: "Charlie'nin bir işe ihtiyacı var! Son derece zeki ve aktif, yürüyüşü seven bir sahip arıyor.",
    tags_en: ["Smart", "Active", "Herder"],
    tags_tr: ["Zeki", "Aktif", "Çoban"],
    adopted: false,
  },
  {
    id: 8,
    name: "Daisy",
    breed: "Persian",
    age: "5 years",
    type: "cat",
    gender: "Female",
    size: "Small",
    image: "https://picsum.photos/id/659/800/800",
    description_en: "Daisy is the queen of the castle. She enjoys grooming and quiet afternoons.",
    description_tr: "Daisy kalenin kraliçesi. Taranmayı ve sessiz öğleden sonralarını sever.",
    tags_en: ["Fluffy", "Calm", "Royal"],
    tags_tr: ["Tüylü", "Sakin", "Asil"],
    adopted: false,
  },
  {
    id: 9,
    name: "Zeus",
    breed: "German Shepherd",
    age: "4 years",
    type: "dog",
    gender: "Male",
    size: "Large",
    image: "https://picsum.photos/id/200/800/800", 
    description_en: "Zeus is a loyal protector. He bonds deeply with his family and loves training.",
    description_tr: "Zeus sadık bir koruyucudur. Ailesine derinden bağlanır ve eğitimi sever.",
    tags_en: ["Loyal", "Protective", "Smart"],
    tags_tr: ["Sadık", "Koruyucu", "Zeki"],
    adopted: false,
  }
];

export const DICTIONARY: Record<Language, TranslationStrings> = {
  EN: {
    nav: {
      home: "Home",
      about: "About",
      pets: "Our Pets",
      donate: "Donate",
      adopt_btn: "Adopt Now",
      back_home: "Back to Home",
    },
    hero: {
      title: "Unconditional Love Awaits",
      subtitle: "Every tail wag and purr tells a story of hope. Find your perfect companion at LokLok today.",
      cta_primary: "Meet the Animals",
      cta_secondary: "How to Help",
      stat_1: "Happy Adoptions",
      stat_2: "Waiting for Love",
    },
    about: {
      title: "About LokLok",
      text: "LokLok was founded with a simple yet powerful dream: to ensure every stray animal finds a safe haven and a loving family. We are more than just a shelter; we are a community of animal lovers.",
      mission: "Our Mission",
      mission_text: "To rescue, rehabilitate, and rehome abandoned animals while promoting responsible pet ownership.",
      vision: "Our Vision",
      vision_text: "A world where every pet has a home and no animal has to suffer on the streets.",
    },
    filters: {
      all: "All Friends",
      dogs: "Dogs",
      cats: "Cats",
      view_all_btn: "View All Pets",
    },
    details: {
      age: "Age",
      gender: "Gender",
      size: "Size",
      about: "About Me",
      adopt_me: "Adopt Me",
      back: "Back",
      health: "Health Status",
      health_text: "Vaccinated, Neutered, Microchipped",
    },
    donate: {
      title: "Make a Difference",
      subtitle: "Your small contribution changes their whole world.",
      card1_title: "Feed a Friend",
      card1_desc: "Provides food for one animal for a week.",
      card1_amount: "$10",
      card2_title: "Medical Care",
      card2_desc: "Covers vaccinations and basic check-ups.",
      card2_amount: "$50",
      card3_title: "Safe Haven",
      card3_desc: "Sponsors shelter and warmth for a month.",
      card3_amount: "$100",
      btn: "Donate Now",
      custom_amount: "Other Amount",
    },
    forms: {
      adopt_title: "Adopt Application",
      adopt_subtitle: "You are applying to adopt",
      donate_title: "Support Our Cause",
      name_label: "Full Name",
      email_label: "Email Address",
      phone_label: "Phone Number",
      message_label: "Why do you want to adopt?",
      amount_label: "Donation Amount",
      card_label: "Card Number (Simulated)",
      submit_adopt: "Submit Application",
      submit_donate: "Process Donation",
      success_title: "Thank You!",
      success_message_adopt: "We have received your application. Our team will contact you shortly to schedule a meeting!",
      success_message_donate: "Your generous donation has been processed. Thank you for helping us save lives!",
      close: "Close",
    },
    stats: {
      title: "Our Impact This Year",
      chart_label: "Adoptions",
    },
    footer: {
      rights: "All rights reserved.",
      contact: "Contact Us",
    }
  },
  TR: {
    nav: {
      home: "Ana Sayfa",
      about: "Hakkımızda",
      pets: "Dostlarımız",
      donate: "Bağış",
      adopt_btn: "Sahiplen",
      back_home: "Ana Sayfaya Dön",
    },
    hero: {
      title: "Koşulsuz Sevgi Seni Bekliyor",
      subtitle: "Her kuyruk sallama ve mırıltı bir umut hikayesi anlatır. Mükemmel arkadaşını bugün LokLok'ta bul.",
      cta_primary: "Tanışmaya Gel",
      cta_secondary: "Nasıl Yardım Edilir",
      stat_1: "Mutlu Yuva",
      stat_2: "Sevgi Bekleyen",
    },
    about: {
      title: "LokLok Hakkında",
      text: "LokLok, basit ama güçlü bir hayalle kuruldu: her sokak hayvanının güvenli bir limana ve sevgi dolu bir aileye kavuşmasını sağlamak. Biz sadece bir barınak değiliz; hayvanseverlerden oluşan bir aileyiz.",
      mission: "Misyonumuz",
      mission_text: "Terk edilmiş hayvanları kurtarmak, iyileştirmek ve sahiplendirmek; aynı zamanda sorumlu evcil hayvan sahipliğini teşvik etmek.",
      vision: "Vizyonumuz",
      vision_text: "Her evcil hayvanın bir yuvası olduğu ve hiçbir hayvanın sokakta acı çekmediği bir dünya.",
    },
    filters: {
      all: "Tüm Dostlar",
      dogs: "Köpekler",
      cats: "Kediler",
      view_all_btn: "Hepsini Görüntüle",
    },
    details: {
      age: "Yaş",
      gender: "Cinsiyet",
      size: "Boyut",
      about: "Hakkımda",
      adopt_me: "Beni Sahiplen",
      back: "Geri Dön",
      health: "Sağlık Durumu",
      health_text: "Aşılı, Kısırlaştırılmış, Çipli",
    },
    donate: {
      title: "Bir Fark Yaratın",
      subtitle: "Küçük katkınız onların tüm dünyasını değiştirir.",
      card1_title: "Bir Dostu Doyur",
      card1_desc: "Bir hayvanın bir haftalık mama ihtiyacını karşılar.",
      card1_amount: "100₺",
      card2_title: "Sağlık Bakımı",
      card2_desc: "Aşıları ve temel sağlık kontrollerini kapsar.",
      card2_amount: "500₺",
      card3_title: "Güvenli Liman",
      card3_desc: "Bir ay boyunca barınma ve ısınma ihtiyacını karşılar.",
      card3_amount: "1000₺",
      btn: "Bağış Yap",
      custom_amount: "Diğer Tutar",
    },
    forms: {
      adopt_title: "Sahiplenme Başvurusu",
      adopt_subtitle: "Sahiplenmek istediğiniz dostumuz:",
      donate_title: "Bize Destek Olun",
      name_label: "Ad Soyad",
      email_label: "E-posta Adresi",
      phone_label: "Telefon Numarası",
      message_label: "Neden sahiplenmek istiyorsunuz?",
      amount_label: "Bağış Tutarı",
      card_label: "Kart Numarası (Simülasyon)",
      submit_adopt: "Başvuruyu Gönder",
      submit_donate: "Bağışı Tamamla",
      success_title: "Teşekkürler!",
      success_message_adopt: "Başvurunuzu aldık. Ekibimiz en kısa sürede sizinle iletişime geçecek!",
      success_message_donate: "Cömert bağışınız alındı. Hayat kurtarmamıza yardım ettiğiniz için teşekkürler!",
      close: "Kapat",
    },
    stats: {
      title: "Bu Yılki Etkimiz",
      chart_label: "Sahiplendirme",
    },
    footer: {
      rights: "Tüm hakları saklıdır.",
      contact: "İletişim",
    }
  }
};

export const ADOPTION_DATA = [
  { name: 'Jan', value: 12 },
  { name: 'Feb', value: 19 },
  { name: 'Mar', value: 15 },
  { name: 'Apr', value: 22 },
  { name: 'May', value: 30 },
  { name: 'Jun', value: 45 },
];
